#!/usr/bin/env python
import os

os.system("clear")
os.system("pkg install ffmpeg")
os.system("cp ivc $PREFIX/bin")
os.system("clear")
print("Proses instalasi selesai!\nKetik 'ivc -h' untuk melihat tutorial")
