#!/usr/bin/env python
import sys, os, math, subprocess
# from subprocess import Popen, PIPE
from datetime import datetime

def get_sec(time_str):
    """Get Seconds from time."""
    h, m, s = time_str.split(':')
    return int(h) * 3600 + int(m) * 60 + int(s)

numberArg = len(sys.argv)
arg1 = str(sys.argv[1])

if(numberArg == 2):
    if(arg1 == "-h"):
        print("""Compress: ivc [namaFile.mp4]
Contoh  : ivc sample.mp4

Trim  : ivc -t [Waktu awal] [Waktu akhir] [namaFile.mp4]
Contoh: ivc -t 00:01:00 00:02:30 sample.mp4

Volume up: ivc -vu [namaFile.mp4]
Contoh   : ivc -vu sample.mp4

Mobile friendly resolution: ivc -m [namaFile.mp4]
Contoh                    : ivc -m sample.mp4

WhatsApp Status Trim: ivc -wa [namaFile.mp4]
Contoh              : ivc -wa sample.mp4

Membatalkan proses kompres: Ctrl + C""")
    else:
        namaFile = arg1
        output = os.path.splitext(f"{namaFile}")[0]
        i = 2
        while(True):
            if(not os.path.exists(f"{output}_compressed.mp4")):
                output = os.path.splitext(f"{namaFile}")[0]
                break
            elif(not os.path.exists(f"{output}_{i}_compressed.mp4")):
                output = output + f"_{i}"
                break
            i = i + 1
        os.system(f'ffmpeg -i "{namaFile}" -c:v libx264 -c:a copy -crf 20 -preset veryfast -metadata comment="Compressed by Instant Video Compressor" "{output}_compressed.mp4"')
        os.system("clear")
        print("Proses kompres selesai")
elif(numberArg == 5):
    if(arg1 == "-t"):
        arg2 = str(sys.argv[2])
        arg3 = str(sys.argv[3])
        arg4 = str(sys.argv[4])
        waktuMulai = arg2
        waktuMulaiSec = get_sec(waktuMulai)
        waktuMulaiSec2 = waktuMulaiSec - 1
        waktuSelesai = arg3
        waktuSelesaiSec = get_sec(waktuSelesai)
        akhir = waktuSelesaiSec - waktuMulaiSec
        namaFile = arg4
        output = os.path.splitext(f"{namaFile}")[0]
        i = 2
        while(True):
            if(not os.path.exists(f"{output}_trim.mp4")):
                output = os.path.splitext(f"{namaFile}")[0]
                break
            elif(not os.path.exists(f"{output}_{i}_trim.mp4")):
                output = output + f"_{i}"
                break
            i = i + 1
        os.system(f'ffmpeg -ss {waktuMulaiSec2} -i "{namaFile}" -ss 1 -t {akhir} -c:v libx264 -crf 20 -preset veryfast -c:a copy -metadata comment="Compressed & trimmed by Instant Video Compressor" "{output}_trim.mp4"')
        os.system("clear")
        print("Proses kompres & trim selesai!")
elif(numberArg == 3):
    if(arg1 == "-vu"):
        arg2 = str(sys.argv[2])
        namaFile = arg2
        output = os.path.splitext(f"{namaFile}")[0]
        i = 2
        while(True):
            if(not os.path.exists(f"{output}_volume_up.mp4")):
                output = os.path.splitext(f"{namaFile}")[0]
                break
            elif(not os.path.exists(f"{output}_{i}_volume_up.mp4")):
                output = output + f"_{i}"
                break
            i = i + 1
        os.system(f'ffmpeg -i "{namaFile}" -c:v libx264 -c:a aac -crf 20 -preset veryfast -filter:a "volume=4.0" -metadata comment="Compressed by Instant Video Compressor" "{output}_volume_up.mp4"')
        os.system("clear")
        print("Proses kompres selesai")
    elif(arg1 == "-m"):
        arg2 = str(sys.argv[2])
        namaFile = arg2
        output = os.path.splitext(f"{namaFile}")[0]
        i = 2
        while(True):
            if(not os.path.exists(f"{output}_resized.mp4")):
                output = os.path.splitext(f"{namaFile}")[0]
                break
            elif(not os.path.exists(f"{output}_{i}_resized.mp4")):
                output = output + f"_{i}"
                break
            i = i + 1
        os.system(f'ffmpeg -i "{namaFile}" -c:v libx264 -c:a copy -filter:v scale="1080:-1" -metadata comment="Compressed by Instant Video Compressor" "{output}_resized.mp4"')
        os.system("clear")
        print("Proses kompres selesai")
    elif(arg1 == "-wa"):
        arg2 = str(sys.argv[2])
        namaFile = arg2
        
        output = os.path.splitext(f"{namaFile}")[0]
        # i = 2
        # while(True):
        #     if(not os.path.exists(f"{output}_wa.mp4")):
        #         output = os.path.splitext(f"{namaFile}")[0]
        #         break
        #     elif(not os.path.exists(f"{output}_{i}_wa.mp4")):
        #         output = output + f"_{i}"
        #         break
        #     i = i + 1
        
        dur = float(subprocess.run(["ffprobe", '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=noprint_wrappers=1:nokey=1',f'{namaFile}'],stdout=subprocess.PIPE).stdout.decode('utf-8'))
        # print(dur)
        # dur = subprocess.run(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 '{namaFile}'", )
        durasi = math.floor(dur)
        if durasi % 30 == 0:
        	perulangan = durasi / 30
        else:
        	perulangan = durasi / 30 + 1
        i = 1
        waktuAwal = 0
        while i <= perulangan:
        	os.system(f'ffmpeg -i "{namaFile}" -ss {waktuAwal} -t 30 -c:v libx264 -c:a copy -crf 20 -preset veryfast -metadata comment="Compressed and Trimmed by Instant Video Compressor" "{output}-{i}-wa.mp4"')
        	i = i + 1
        	waktuAwal = waktuAwal + 30
        if os.path.exists(f"{output}-1-wa.mp4"):
	        os.system('clear')
	        print("Trim success!")
        	print(f"Result: {math.floor(perulangan)} files")
        else:
	        print("Trim failed!")