#!/usr/bin/bash
if [ $# -eq 1 ]; then
	namaFile=$1
	output=${namaFile%.*}
	ffmpeg -i "$namaFile" -c:v libx264 -c:a copy -crf 20 -preset veryfast -metadata title="Compressed by Instant Video Compressor" "${output}_compressed.mp4"
	#echo $output
	echo -e "\nProses kompres selesai!"
elif [ $# -eq 4 ]; then
	if [ "$1" -eq "-t" ]; then
		waktuMulai=$2
    waktuMulaiSec=$(echo $waktuMulai | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
  	waktuMulaiSec2=$(echo $waktuMulai | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 - 1 }')
		waktuSelesai=$3
		waktuSelesaiSec=$(echo $waktuSelesai | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
		akhir=$(expr $waktuSelesaiSec - $waktuMulaiSec)

		namaFile=$1
		output=${namaFile%.*}
    ffmpeg -ss $waktuMulaiSec2 -i "$namaFile" -ss 1 -t $akhir -c:v libx264 -crf 20 -preset veryfast -c:a copy -metadata title="Compressed & trimmed by Instant Video Compressor" "${output}_trimmed.mp4"
		echo -e "\nProses kompres & trim selesai!"
	fi
fi
